### PR TITLE
Rename during CppSharp generation

### LINKED ISSUE #5: Renaming
After the "mission-critical" issues are addressed, are you okay with me setting up some name cleaning in the generator project?

Example:
```cs
public enum NfdresultT
{
    NFD_ERROR = 0,
    NFD_OKAY = 1,
    NFD_CANCEL = 2
}
public enum NfdResult
{
    Error = 0,
    Okay= 1,
    Cancel = 2
}
```

### PR DESCRIPTION
**Pull request by ds5678**
Resolves #5

### CODE REVIEW

**Review by Speykious — APPROVED** [review]
LGTM

**Comment by Speykious** [comment]
I'll probably publish a version 2.0.0 in a couple days if all goes well, though before that I'd like to see if I can't make it work on Mac.

**Comment by ds5678** [comment]
Sounds good

**Comment by ds5678** [comment]
Thank you for all you've done, both in the past couple weeks and prior to me finding the project.

**Comment by Speykious** [comment]
you're welcome :D

**Comment by ds5678** [comment]
BTW if you want a little more recognition for the project, CppSharp has a readme section dedicated to users like us.

https://github.com/mono/CppSharp?tab=readme-ov-file#users

**Comment by ds5678** [comment]
> I'll probably publish a version 2.0.0 in a couple days if all goes well, though before that I'd like to see if I can't make it work on Mac.

How are things going?

**Pull request merged**
